#!/bin/sh

FG="$(xgetres foreground)"
BG="$(xgetres background)D0"
COLOR1="$(xgetres color1)"
COLOR2="$(xgetres color2)D0"
COLOR4="$(xgetres color4)"
COLOR10="$(xgetres color10)"
COLOR11="$(xgetres color11)"
TRANS="#00000000"

DATE_FORMAT="%a, %b %d"
TIME_FORMAT="%I:%M:%S"

FONT="monospace"


[ "$1" = "-n" ] || BLUR="--blur=3"

[ "$1" = "-h" ] && printf \
"Usage:
	-n\t\t\"no blur\", allows you to blur the background using a compositor like picom
	-h\t\tshow this help message\n" && exit 0


i3lock \
--color="$TRANS" \
--ignore-empty-password \
--pass-media-keys \
--pass-screen-keys \
--pass-volume-keys \
--pass-power-keys \
--indicator \
--nofork \
--clock \
--radius=120 \
--ring-width=14 \
--time-size=38 \
--time-str="$TIME_FORMAT" \
--date-size=18 \
--date-str="$DATE_FORMAT" \
--time-font="$FONT" \
--date-font="$FONT" \
--no-modkey-text \
--noinput-text="" \
--verif-text="" \
--wrong-text="" \
--lock-text="" \
--lockfailed-text="" \
--line-uses-ring \
--time-color="$FG" \
--date-color="$FG" \
--insidewrong-color="$BG" \
--insidever-color="$BG" \
--inside-color="$BG" \
--ringwrong-color="$COLOR1" \
--ringver-color="$COLOR4" \
--ring-color="$COLOR2" \
--separator-color="$FG" \
--keyhl-color="$COLOR10" \
--bshl-color="$COLOR11" \
$BLUR
