#!/bin/sh

BG="#00000000"
RED="$(xgetres color1)"
GREEN="$(xgetres color2)D0"
BLUE="$(xgetres color4)"
LIGHT_GREEN="$(xgetres color10)"
YELLOW="$(xgetres color11)"
CIRCLE_BG="$(xgetres background)D0"
CIRCLE_FG="$(xgetres foreground)"
DATE_FORMAT="%a, %b %d"
FONT="monospace"


[ "$1" = "-n" ] || BLUR="--blur=3"

[ "$1" = "-h" ] && printf \
"Usage:
	-n\t\t\"no blur\", allows you to blur the background using a compositor like picom
	-h\t\tshow this help message\n" && exit 0


i3lock \
--color=$BG \
--ignore-empty-password \
--pass-media-keys \
--pass-screen-keys \
--pass-volume-keys \
--pass-power-keys \
--indicator \
--nofork \
--clock \
--radius=115 \
--ring-width=16 \
--layout-size=14 \
--time-size=38 \
--date-size=18 \
--date-str="$DATE_FORMAT" \
--layout-font="$FONT" \
--time-font="$FONT" \
--date-font="$FONT" \
--no-modkey-text \
--noinput-text="" \
--verif-text="" \
--wrong-text="" \
--lock-text="" \
--lockfailed-text="" \
--keylayout=1 \
--line-uses-ring \
--layout-color="$CIRCLE_FG" \
--time-color="$CIRCLE_FG" \
--date-color="$CIRCLE_FG" \
--insidewrong-color="$CIRCLE_BG" \
--insidever-color="$CIRCLE_BG" \
--inside-color="$CIRCLE_BG" \
--ringwrong-color="$RED" \
--ringver-color="$BLUE" \
--ring-color="$GREEN" \
--separator-color="$CIRCLE_FG" \
--keyhl-color="$LIGHT_GREEN" \
--bshl-color="$YELLOW" \
$BLUR
